###############################################################################
#                          Generated on Agência Show                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: "${APP_NAME}-mysql"
      working_dir: /application
      volumes:
        - .:/application
        - ./mysql-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "${MYSQL_PORT}:3306"

    webserver:
      image: nginx:alpine
      container_name: ${APP_NAME}-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "${NGINX_PORT}:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: ${APP_NAME}-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

